### ISSUE TITLE
Add HTTPS support

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#114]
Secure connections would be nice, especially for admin.
Let's Encrypt could be the easiest way to add this: https://letsencrypt.org
~~At this moment it is still in (public) beta.~~

**Comment by 153957** [comment]
Probable solution:

Certbot - https://certbot.eff.org/
- Using the webroot verification method.
- Setup cronjob to automatically renew and touch reload uwsgi as post hook.

uWSGI config - http://uwsgi-docs.readthedocs.io/en/latest/HTTPS.html#https-support-from-1-3
- Add the /.well-known/ location to static-map, for some location for certbot to write verification to.
- Add https option pointing to the created certificates.

Might be easier to just add NGINX in front of uWSGI.

**Comment by tomkooij** [comment]
I have looked into this some time ago. I remember it was quite is to `hack` a certbot / webroot solution.

But for maintainability I think we need to add `nginx`, so we can use an out-of-the-box solution.

**Comment by 153957** [comment]
Agreed, so nginx first, then certificates.
