### ISSUE TITLE
MySQL password provisioning broken for ansible 2.0

### ISSUE THREAD

**Issue by davidfokkema** [HiSPARC/publicdb#115]
Using ansible 2.0, the vagrant boxes can no longer be provisioned successfully. Ansible 1.9.4 works fine. It has something to do with the mysql_user module. Maybe it accepts different parameters?

**Comment by 153957** [comment]
Multiple reports of issues with mysql_user in ansible 2.0, they seem to be resolved:
ansible/ansible-modules-core#1215
ansible/ansible-modules-core#2804
So, wait for the next release of ansible 2.

**Comment by davidfokkema** [comment]
Ah, that would be great!

**Comment by 153957** [comment]
(@tomkooij)

**Comment by 153957** [comment]
Works with ansible 2.1 and latest publicdb master including 85b2683
