### ISSUE TITLE
Add verification of Nagios config?

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#116]
Should the provisioning perhaps run a check of the nagios configuration?

```
nagios -v /etc/nagios/nagios.cfg
```

~~Currently reports:~~
~~Error: Cannot open resource file '/etc/nagios/private/resource.cfg' for reading!
Error in configuration file '/etc/nagios/nagios.cfg' - Line 470 (Check result path is not a valid directory)~~

**Comment by 153957** [comment]
Ah nevermind, those errors were due to permission issues (ran them as hisparc.)

**Comment by davidfokkema** [comment]
You have to run this as user 'nagios', or as root.

**Comment by davidfokkema** [comment]
Yes, exactly, ;-).
