### ISSUE TITLE
Do not update to numexpr 2.4.6/2.5

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#131]
I updated SAPPHiRE today, it also updated numexpr 2.5, this caused data downloads to fail with the following traceback:

```
Traceback (most recent call last):
  File "../django_publicdb/raw_data/views.py", line 267, in generate_events_as_tsv
    for events, reconstructions in events_reconstructions:
  File "../django_publicdb/raw_data/views.py", line 321, in get_events_from_esd_in_range
    with tables.open_file(filepath) as f:
  File "/srv/publicdb/publicdb_env/lib/python2.7/site-packages/tables/file.py", line 318, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/srv/publicdb/publicdb_env/lib/python2.7/site-packages/tables/file.py", line 835, in __init__
    numexpr.set_vml_num_threads(params['MAX_NUMEXPR_THREADS'])
  File "/srv/publicdb/publicdb_env/lib/python2.7/site-packages/numexpr/utils.py", line 74, in set_vml_num_threads
    _set_vml_num_threads(nthreads)
SystemError: Objects/methodobject.c:120: bad argument to internal function
```

I downgraded numexpr back to <2.5.

_edit: Oops, I originally posted the wrong traceback.. that was for another error_

**Comment by 153957** [comment]
Do not upgrade to numexpr 2.4.6 either, it also contains some bugs

**Comment by tomkooij** [comment]
The conda packages numexpr >= 2.4.6 seem broken. Either install it locally or ```conda install numexpr=2.4.4```

**Comment by 153957** [comment]
I downgraded publicdb to 2.4.4. I wont install locally, because we want to use conda, it should just work :P

**Comment by tomkooij** [comment]
It might have something to do with MKL optimisations: https://docs.continuum.io/mkl-optimizations/index

The numexpr-2.4.4 package does not depend on MKL and from 2.4.6 it does. 
I tried:
```conda install nomkl numpy scipy numexpr```

Which replaces MKL with OpenBLAS. This resolves the log10() query problems. 

Not sure this is a MKL thing or just a package problem. I'm not sure my locally compiled numexpr uses MKL. It is something to keep under consideration when encountering bugs.

I reported this to Anaconda.

**Comment by 153957** [comment]
Where did you report it? I do not see an issue in the anaconda-issues repo; https://github.com/ContinuumIO/anaconda-issues/issues?utf8=✓&q=

**Comment by tomkooij** [comment]
Ah! I used the anaconda newsgroup, link was on the webpage. Will use the github (didn't know it existed, couldn't find it).

Meanwhile, I figured out it has to do with the Intel Math Kernel Library (MKL). If I install a local numexpr and build it with MKL (major pain in the ...) it fails as well.
numexpr=2.4.4 is the last conda package that does not have MKL by default.
Unfortunately MKL is about 5x faster than OpenBLAS, so it is nice to have.

I haven't found the actual bug, but it might be SELinux preventing MKL to run, this is a known problem and MKL is "Enforced" on CentOS.

I will try SELinux settings on my local box (perhaps tonight) and see if that is the problem. If not I'll try to identify the bug more closely and report it to PyTables/NumExpr

**Comment by tomkooij** [comment]
https://gist.github.com/tomkooij/461de490f60e290d201d9c8eefc6c90f

This is a test for the bug without depending on pytables (but simulating read_where() using a recarray). This fails on Linux-64 and Windows 10, with local builds of numexpr. I will report this to numexpr.

I'm quite sure it has to do with memory mapping. Unfortunately I have no clue how to inspect this with gdb.

**Comment by tomkooij** [comment]
Unfortunately this is not fixed in numexpr 2.5.1. ```numexpr.evaluate()``` is fixed, but that is not what pytables.read_where() uses.

**Comment by 153957** [comment]
Is this fixed in PyTables 3.2.3(.1) with numexpr 2.6?

**Comment by tomkooij** [comment]
Yes!

**Comment by 153957** [comment]
Ok, good, unfortunately pytables 3.2.3+ is not yet on conda..

**Comment by tomkooij** [comment]
pytables 3.2.3.1 is on conda.
