### ISSUE TITLE
Make singles data available to users

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#134]
The datastore now stores singles data, which is data reported every second by stations which run the latest station-software. Each second the number of singles over the low and high thresholds for each channel is reported. This is stored in the 'singles' table. 
This data can be added to the esd (it needs to be cleaned, i.e. sorted by timestamp). And be added as a new data type for downloading.

Next year a LiO might be working on a project which involves looking into the singles data.

**Comment by tomkooij** [comment]
#160
