### ISSUE TITLE
Unique station offsets

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#140]
The `hisparc-update` crashed when trying to save station offsets, complaining that two matched a `get` query (from `StationTimingOffset.objects.update_or_create`, which calls a get to try and get a model to update, otherwise it creates a new model). Probably caused by multiple simultaneous jobs trying to same the offsets for the same station combinations for the same date, which caused two to be created.

We still need to add the unique restriction to the station offsets: `unique_together = ('ref_source', 'source')`. That would probably fix this, but will require a new migration.

**Comment by tomkooij** [comment]
doh! I did not realise that ```unique_together``` was needed when creating the migration.

What bothers me, is that I checked last nights run of ```hisparc-update``` this morning and decided it had finished sucessfully. What did I miss?

**Comment by 153957** [comment]
That is no problem, we can just make a new migration that adds the 'unique_together' property.

Last night went fine, but I reran it this morning because Niek's station 104 just uploaded several days of data, and we wanted to check if it was properly received. That is when the error occurred.

**Comment by 153957** [comment]
Should be fixed now; 732074e46553366e5d36a65aac41841fb422545b,  9744c1a0839af3e2cce190313971804941ed3270
