### ISSUE TITLE
CSS / layout issue on Chrome/Win10

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#147]
The sidebar on station pages starts at the wrong "height", firefox is ok.

![image](https://cloud.githubusercontent.com/assets/6316468/17822171/c87b156c-6655-11e6-9487-58390f3557d5.png)

![image](https://cloud.githubusercontent.com/assets/6316468/17822150/aa49a84c-6655-11e6-92c6-4009444a8ee5.png)

```
Google Chrome	52.0.2743.116 (Officiële build) m (64-bits)
Revisie	9115ecad1cae66fd5fe52bd9120af643384fd6f3-refs/branch-heads/2743@{#728}
Besturingssysteem	Windows 
Blink	537.36 (@9115ecad1cae66fd5fe52bd9120af643384fd6f3)
JavaScript	V8 5.2.361.49
Flash	22.0.0.209
User-agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
```

**Comment by 153957** [comment]
No issue on El Capitan with Chrome 52.
If I zoom to less than 100%, e.g. 90%, it does move the sidebar down.
Please check your zoom level to ensure you are at 100%.

**Comment by 153957** [comment]
I opened your screenshots at full size and they are smaller than the 100% version of the page in my browser. So it is an issue when zooming out..
