### ISSUE TITLE
Coincidence download can timeout before downloads starts

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#148]
Downloading coincidences for three stations (eg 501, 502, 508) from a large timeframe (2008-2016) fails before download starts. 

There seems to be a 1-minute timeout, but gathering coincidences seems to take longer.

**Comment by 153957** [comment]
Probably a browser timeout, takes server some time to find any eligible coincidences.
Currently the function getting the coincidences ([get_coincidences_from_esd_in_range](https://github.com/HiSPARC/publicdb/blob/master/django_publicdb/raw_data/views.py#L641)) only checks if the NetworkSummary exists before using CoincidenceQueries, perhaps it should also check for the minimum required number of Summaries (possibly less if you allow stations to have coincidences with themselves) with events for the chosen stations.

**Comment by tomkooij** [comment]
sapphire/download_coincidences suffers from the same timeout. If this is a timeout on the recieving end, I need to open an issue at sapphire.  (Meanwhile I'll just download in smaller parts).

**Comment by 153957** [comment]
The timeout is on the receiving end, but it also a problem for users using the browser download.
I think the algorithm on the publicdb can be optimised to be quicker in rejecting days in which there is no chance for coincidences (require at least n or two different stations with some data).
Indeed, splitting in smaller parts can also help. Could be implemented in SAPPHiRE to automatically split downloads in months/half years/years.

**Comment by tomkooij** [comment]
I'm doing years now, but unfortunately, generating takes >60 secs which causes a timeout.  I haven't been able to either (re)set or catch the timeout.

This is from `pique:var\log\uwsgi.log`
2012, n=3, [102, 104, 105]
The query takes 101 seconds.
```
GET /data/network/coincidences/?stations=%5B102%2C+104%2C+105%5D&start=2012-01-01+00%3A00%3A00&end=2013-01-01+00%3A00%3A00&cluster=None&n=3 => generated 1545 bytes in 101057 msecs
```
The second query is much faster, so I'm doing:
```
while failed:
   try:
       download_coincidence(...)

**Comment by 153957** [comment]
Second time is likely faster because some disk data will be cached.
In SAPPHiRE you could try to catch a timeout and try again, similar to how the BadStatusLine is caught and another download is attempted: https://github.com/HiSPARC/sapphire/blob/master/sapphire/esd.py#L384

However, I would advice to go with the split by month approach.

**Comment by tomkooij** [comment]
No priority.
