### ISSUE TITLE
Pulseheight histograms for 504 missing ch3 and ch4

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#149]
The PH histograms  for station 504 are missing ch3 and ch4, at least on september 10 and 11 2016:
http://data.hisparc.nl/show/stations/504/2016/9/10/
September 9 2016 is fine, showing four channels.

I haven't checked if it's in the data or processing.

Needs investigating.

**Comment by 153957** [comment]
Given the low number of events and the clear trigger edge at ~70mV pulse height it is likely that the Slave unit is not active. Probably a failed or disconnected power supply, or simply a connection loss which may be solved by restarting the DAQ/PC. (If the power was temporarily disconnected to the Slave the firmware needs to be reloaded, i.e. restarting the DAQ.)

**Comment by tomkooij** [comment]
Thanks for the diagnosis! This might be something for @kaspervd.

**Comment by 153957** [comment]
Indeed 😄

**Comment by tomkooij** [comment]
Fixed.
