### ISSUE TITLE
Transition to Python 3

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#155]
Python 2 will be end-of-life in a few years.
The publicdb should be transitioned to Python 3.
SAPPHiRE is already Python 3 compatible.
publicdb does not need to keep backwards compatible with Python 2.

See discussion at: https://github.com/HiSPARC/sapphire/pull/154#issuecomment-257255562

**Comment by 153957** [comment]
Django will no longer support Python 2.7 after Django 1.11, support already being removed in Django master branch:
https://github.com/django/django/commit/f6acd1d271122d66de8061e75ae26137ddf02658

**Comment by 153957** [comment]
Reminder: do not forget to update the 'remove compiled code' when deploying the publicdb after upgrading to Python 3. For Python 3 `__pycache__` directories should be removed.

**Comment by 153957** [comment]
Currently the histograms/coincidences/datasets use a SerializedDataField which uses pickling, I will attempt to replace these by PostgreSQL Array/JSON Fields, so that should then not be an issue...

**Comment by 153957** [comment]
This project has been upgraded to Django 1.11.
SerializedDataField has been replaced by ArrayFields.

**Comment by 153957** [comment]
Python 2 is no longer supported.

**Comment by davidfokkema** [comment]
This is really an issue now.

**Comment by 153957** [comment]
Note; Django 1.11 is supported until April 2020, and Django 2.2 (LTS) required Python 3.
