### ISSUE TITLE
Vagrant (ansible) fails on git-crypted data for test-VM

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#157]
vagrant (ansible) fails (chokes on utf-8) on git-crypted data in `provisioning/host_vars/pique.nikef.nl` when setting up a test `publicdb` VM locally.

```
==> publicdb: Running provisioner: ansible_local...
    publicdb: Running ansible-playbook...
ERROR! Unexpected Exception: 'utf8' codec can't decode byte 0xe5 in position 11: invalid continuation byte
to see the full traceback, use -vvv
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Ideally this should not happen while provisioning a `publicdb` test VM.

Note to future self: just empty the file.

**Comment by davidfokkema** [comment]
It only fails when someone does *not* have the encryption key, right? If the repository is unlocked, it works perfectly AFAICT.

**Comment by tomkooij** [comment]
@davidfokkema It does. However, the encryption key is only needed when provisioning `pique.nikhef.nl`. Setting up a *test VM* publicdb should not require the key. 

Although it should be possible to untangle the publicdb group and pique host in ansible, this is certainly not necessary: We can spend our time on more useful stuff.

The annoying thing is that ansible chokes on the encrypted file, which is hard to debug. Hence this issue as a reminder. Perhaps explicit instructions in `README.rst` on using `git-crypt` (and/or the ansible error) is a better solution.

**Comment by davidfokkema** [comment]
It is a long-standing bug that ansible tries to read all files containing variables, even if it doesn't need them for the groups and hosts which are being provisioned. Sigh. I agree that it should ideally be possible to checkout the publicdb repository and provision a test machine without knowing the key to the passwords being used for pique.
