### ISSUE TITLE
Publicdb source download: CRLF / LF

### ISSUE THREAD

**Issue by davidfokkema** [HiSPARC/publicdb#16]
Nice! The csv-files that can be downloaded by clicking on the source buttons on the data pages returns files with unix-style line breaks: LF. Windows doesn't get that, it wants CRLF. Fix that platform independently???

**Comment by 153957** [comment]
Partially 'fixed' in 7390b48. At least all TSV files now use LF exclusively.
We can change that to CRLF, but then need to do some fancy things with `.gitattributes` to force TSV files to have CRLF line endings on checkout, even on Linux.
We do not have much issues with LF, only Notepad does not recognise it as a valid line break, WordPad and Excel do.
