### ISSUE TITLE
VM fails to build

### ISSUE THREAD

**Issue by davidfokkema** [HiSPARC/publicdb#161]
See conda/conda#4593.

**Comment by 153957** [comment]
Fixed with conda 4.3.12?

**Comment by davidfokkema** [comment]
Nope. New error... See conda/conda#4621, further down (AssertionError).

**Comment by davidfokkema** [comment]
Temporarily worked around using by 6df26e6d1bb152cdffb27bd5ead81ad66c82b5e2.
