### ISSUE TITLE
Issues with thresholds reported on data pages

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#163]
See: http://data.hisparc.nl/show/stations/201/2017/2/16/
The values are in mV.

Also there is a colon after the text, which is not there for the other listed items.

**Comment by tomkooij** [comment]
@153957. Thanks for spotting this... (ouch!). I'll fix it.

I'm not seeing the colon. But I'll look into it.

**Comment by 153957** [comment]
![colon](https://cloud.githubusercontent.com/assets/1433682/23065126/39260720-f514-11e6-883c-82e6c015f03f.png)

**Comment by 153957** [comment]
See https://github.com/HiSPARC/publicdb/blob/master/django_publicdb/status_display/templatetags/fix_data.py#L93

Simply use that templatetag on the values, similar to the way it is used here:
https://github.com/HiSPARC/publicdb/blob/master/django_publicdb/status_display/templates/source_trigger_config.tsv#L19

**Comment by tomkooij** [comment]
Thanks for pointing this out. I really did not spot the colon...

I think I'll leave the values in mV as they are in mV in the DAQ.

**Comment by 153957** [comment]
Nope, newer versions of the DAQ (v4.[something]) report the thresholds as ADC.
See for example this station with the new software: http://data.hisparc.nl/show/stations/501/2017/2/19/
It reports the values correctly in ADC.

I would vote for the implementation of #45: Use ADC in all cases (instead of mV). Since that is also the units used in the downloadable data files.

**Comment by tomkooij** [comment]
I am writing student-material that references the threshold values in the DAQ software (on the screen of the station computer). Those are in mV. Hence, my choice for mV. But these turn out to be different  thresholds... 

I need to figure out was it all means... 

(But I agree with use ADC in all cases).

**Comment by 153957** [comment]
Indeed, the DAQ interface still uses mV.
Perhaps include in the material a small explanation about the working of the ADCs; 12-bit output range for ~2 Volt input range. Provides a certain conversion factor. But because the traces are read as ADC those units are used in the analysis, and that is how the thresholds are reported to the datastore.

However, that might be to in-depth and perhaps off-topic...

**Comment by tomkooij** [comment]
I'm still confused.

HiSPARC III electronics uses a baseline of 30:
``` 
def mv_to_adc(mv):
    return int(mv / -0.584 + 30)
```
HiSPARC II uses 200 baseling:
```
def mv_to_adc(mv):
    return int(mv / -0.57 + 200)
```

It seems that there are two different ADC units in HiSPARC. Each with different conversion factor to mV.
- 203 (HiSPARC II, latest DAQ): [253 ADC 323 ADC](http://data.hisparc.nl/show/stations/203/2017/2/19/)
- 4 (HiSPARC III - serial 4xx !, latest DAQ): [81 ADC 150 ADC](81 ADC 150 ADC)

And mVs:
- 501 (HiSPARC III, latest DAQ): [56 ADC 150 ADC] (http://data.hisparc.nl/show/stations/501/2017/2/19/)
- 509 (HiSPARC III, old DAQ): [-30 ADC -70 ADC](http://data.hisparc.nl/show/stations/511/2017/2/19/)

**Comment by 153957** [comment]
The 56 ADC low threshold is lower than then 81 ADC threshold because it was lowered for station 501, to (approx) -15mV, instead of the usual (approx) -30 mV). So those are correctly different from the usual 81 ADC.

Indeed, there are different conversions. But the conversions should be those you references for the given HiSPARC type (II or III). Possible new conversions (used by the DAQ) should be covered in the HiSPARC Monitor in the station software because it uses values provided by the DAQ to convert the mV thresholds to ADC:
- https://github.com/HiSPARC/station-software/commit/2d0bd92f9045380d2a851f832ef97a6b2744761e
- https://github.com/HiSPARC/station-software/commit/fa82ec42d507f26614d07537bbd77850880ef2e1

**Comment by tomkooij** [comment]
@153957 : Thanks.

So https://github.com/HiSPARC/publicdb/blob/master/django_publicdb/status_display/templatetags/fix_data.py#L93 is only valid for HiSPARC II electronics, right?

Unfortunately, the electronics versions is not known by the filter. It is discoverable, of course, but...

Perhaps I'll create a filter that adds the unit: ADC for positive values and mV for negative values.

**Comment by 153957** [comment]
The units should be constant, otherwise it will be hell during an analysis.
And they should be correct, because the [trigger settings TSV data](https://github.com/HiSPARC/publicdb/blob/master/django_publicdb/status_display/templates/source_trigger_config.tsv#L19) is used by the ProcessEvents to [perform trigger time reconstruction]( https://github.com/HiSPARC/sapphire/blob/master/sapphire/analysis/process_events.py#L688).

**Comment by tomkooij** [comment]
Thanks again for taking the time, to fix my confusion. I agree that it obviously correct, since trigger time reconstruction seems to be ok, but:

 - 501: -15 mV / -0,584 + 30 = 56 ADC 
 - The [ filter in publicdb ](https://github.com/HiSPARC/publicdb/blob/master/django_publicdb/status_display/templates/source_trigger_config.tsv#L19)uses mV/-0,57 + 200

How can they both be correct?

**Comment by 153957** [comment]
For 501 only the first conversion is correct, but the new values for 501 are reported in ADC to the datastore (and then publicdb), so no additional conversion needs to happen in that case, so the template filter does no conversion, is sees a positive value.

I agree that the template filter is incomplete, it does not account for all possible situations.

However, in most cases where new HiSPARC III electronics were used with an old DAQ the conversion is correct. The new DAQ which officially supports HiSPARC III was released with the new monitor which converts the values to the correct units (ADC). It may have been installed on some stations prior to the modifications to the monitor, i.e. 501 (which was fixed by the datastore migration)....

**Comment by tomkooij** [comment]
@153957: Is the description in 4167674 correct? 

(I will stop force pushing a commit that references this repo...)

**Comment by 153957** [comment]
I would clarify the behaviour of HiSPARC II in the new DAQ, and note the actual version number of the DAQ, which was a bit vague before v4, so just call them 'before v4'. Also clarify that the HiSPARC Monitor uses values supplied by the DAQ:

```
Old DAQ (before v4):
- HiSPARC II+III => ADC = mV / -0.57 + 200
New DAQ:
- HiSPARC II => ADC = mV / -0.57 + 200
- HiSPARC III => ADC = mV / -0.584 + 30

Old versions of the DAQ report thresholds in mV. For both
HiSPARC II and III the baseline is 200 with the old DAQ.

For new versions of the DAQ the bundled HiSPARC Monitor converts
the thresholds to ADC using the conversions supplied by the DAQ.

If value < 0: Assume mV and convert to ADC assuming the baseline 200.
```

The description for the migration also clarifies this transition: https://github.com/HiSPARC/datastore/blob/master/migration/migrate_fix_configs.md#160304---convert-mv-thresholds-to-adc-for-baseline-at-30-adc-counts
