### ISSUE TITLE
Difference in processing for low/high singles

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#166]
Why are the high rates also 'stacked' after the shrink, while the low rates are not?

https://github.com/HiSPARC/publicdb/blob/master/django_publicdb/histograms/jobs.py#L604-L610

And might it be a good idea to round the mean single rates to an integer when processing them?
*(Note: I already modified the TSV source template to round to integers)*

**Comment by tomkooij** [comment]
Thanks! The code should be exactly the same for high/low singles, excepted for the low/high reference. Should have done solved that DRY...  

Will fix.

**Comment by 153957** [comment]
Also, please extract the `def shrink` from the `update_singles_rate_dataset` function :)

**Comment by tomkooij** [comment]
Mmhh... Too late :) I'm leaving the function in for now. It's really only meant for keeping the function DRY and no use for other functions. (If I extract it, it needs a better docstring etc etc).

Fixed in 6392de0
