### ISSUE TITLE
Fix provisioning: adding user to group

### ISSUE THREAD

**Issue by davidfokkema** [HiSPARC/publicdb#167]
Finally: ansible/ansible-modules-core#921. Fix this in our provisioning scripts, but starting with ansible 2.3, which is not yet available via Homebrew.

**Comment by 153957** [comment]
It is now 😄 
```
$ brew info ansible
ansible: stable 2.3.2.0 (bottled)
```

**Comment by davidfokkema** [comment]
Yes, and I have fixed this in PySPARC. This needs some attention!

**Comment by tomkooij** [comment]
This seems solved in 2e39a576f7d252b8103908a8f9217c0338e3861c
