### ISSUE TITLE
Suggestion: switch to linear scale in pulseheight histogram

### ISSUE THREAD

**Issue by kaspervd** [HiSPARC/publicdb#173]
The peak due to low-energy gammas in the pulseheight histogram is very large, I think for this reason a logarithmic scale was chosen?

The peak is mainly due to noise (if 2 or 3 detectors have triggered the last detector(s) always store 1,2 or 3 ADC counts instead of 0). I think we should regard all data below 10 (or so) ADC counts as noise and remove them from the histograms. If this is done there is no reason to go for a logarithmic scale.

What do you thinks?

**Comment by 153957** [comment]
I disagree. On a linear scale the tail of events at high pulseheights would be hard to see. For stations with only 2 detectors the 'peak' is not that much higher than the MIP peak: 
![unknown-1](https://cloud.githubusercontent.com/assets/1433682/24459601/436ddbde-149c-11e7-96f7-4a0ddbe872f2.png)

Currently you can still see that there are some events with pulseheights which (almost) saturate the ADCs, which will be hard on a linear scale:

![unknown-2](https://cloud.githubusercontent.com/assets/1433682/24459642/5fe277fc-149c-11e7-8e36-e5e2c4e79782.png)

![unknown](https://cloud.githubusercontent.com/assets/1433682/24459648/63686030-149c-11e7-9a02-fdfcb30b3077.png)

**Comment by kaspervd** [comment]
This becomes more evident if you drastically increase the number of bins but that's ugly. So yes, let's keep things as they are.
