### ISSUE TITLE
Cannot reach local dev publicdb VM with browser

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#177]
http://192.168.99.11/ is the IP address of my local `publicdb` VM as managed by Vagrant.

At a3924ae  I cannot reach my local VM with a browser anymore. No connection (timeout, not refursed) with telnet to port 80 as well.

I cannot easily test a *last known good* configuration (should be 746d210abdf7d31e3d5168a36e874daa3ea9ffad) because that tries to checkout the current master when provisioning, which then fails (`publicdb_django` changed to `publicdb`). The datastore VM also works, so I'm not expecting this to be a local firewall issue.

Does this still work on your VM, @153957 ?

**Comment by 153957** [comment]
Yes, no problems for me.

Only problem for me is that 6acbbdce999173ab63234ba538c8eacb5db77035 does not yet work as I had hoped. It seems to checkout the origin/HEAD of the local repo instead of the HEAD (currently active checkout/commit).

**Comment by 153957** [comment]
Which version of Ansible do you have?

I changed some things in af3e4ffe3756ea06972e326c8b34d23adb0475e3 which require Ansible 2.x..

**Comment by tomkooij** [comment]
`ansible 2.2.1.0`

I'm not sure what's going on. My datastore VM works fine, but even a fresh publicdb VM is unreachable over HTTP to 192.168.99.11, but I can ssh into it...

I don't have time to investigate, but I'm leaving this open, because it needs fixing. I cannot use my publicdb VM right now.

**Comment by tomkooij** [comment]
Its probably a `django` version thing. Adding '192.168.99.11' to `ALLOWED_HOSTS` in settings.py solves this. 

I'll see if I can fix it.

**Comment by 153957** [comment]
Ah, you were not using 127.0.0.1:8081 in your browser?
In newer versions of Django it strictly checks for `ALLOWED_HOSTS`.
See: 5cdf4f0ded549da381d8c35baa61c40f0f1cddfc.
You can also add that local ip to the `ALLOWED_HOSTS` if `DEBUG`.
Or just access it via localhost..

**Comment by tomkooij** [comment]
Ok... That's reasonable.

I'll add `192.168.99.11` to the if `DEBUG`. Since you can SSH into 192.168.99.11 it's awkward to not be able to use HTTP to connect to it.
