### ISSUE TITLE
Rebooting a Vagrant VM from an ansible handler breaks mounted volumes

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#192]
When provisioning the publicdb VM it performs the 'upgrade all packages' task. After which a check is performed to see if the kernel was updated, if so a reboot is flagged. However, after the reboot the provisioning continues but breaks when trying to clone `/vagrant/.git` because the `/vagrant` mount is no longer working, because vagrant did not perform the reboot.

Perhaps the reboot can be delayed until the end of provisioning. After which you would still need to reboot the VM using vagrant to remount `/vagrant`..

**Comment by davidfokkema** [comment]
Does a vagrant halt/up cycle restore the mount? Otherwise the problem is even nastier...

**Comment by 153957** [comment]
Yes it does, also `vagrant reload` restores the mount, and if you pass the `--provision` flag it should be fine. This also happens when you use VirtualBox to shutdown/start/.. the VM instead of using vagrant as managing interface, since VirtualBox is not aware of the Vagrant settings.

Currently only a problem for the publicdb VM where `/vagrant` is actually used.

**Comment by 153957** [comment]
Possibly fixed with 6ea1183 (needs some testing)
