### ISSUE TITLE
jSPARC analysis sessions broken: event data missing.

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#193]
jSPARC analysis sessions are failing. (Both "get example" and actual requested sessions).

In the JSON that is returned by `http://data.hisparc.nl/jsparc/get_coincidence/?session_title=example&session_pin=1337&student_name=test` the event data seems to be missing:

```json
 "events":
 [{"status": "on",
 "timestamp": 1393725788,
 "altitude": 57.5165005522,
 "detectors": 0,
 "number": 502, 
"longitude": 4.95009211145,
 "integrals": [],
 "mips": [],
 "latitude": 52.3552939665,
 "pulseheights": [],
 "traces": [],
 "nanoseconds": 163936473},
```
The `traces`, `integrals`, `mips` are all empty lists, which results in reconstructed energy being 0 and everything failing.

Requested sessions have same result. I tried a day for which the stations have normal data.

**Comment by davidfokkema** [comment]
Any idea if this is only for new data? Or maybe something changed in the publicdb code? Or is it just jsparc?

**Comment by 153957** [comment]
The data is also missing in the database. I do not know how that happened, possibly while migrating to Postgres, but that seems strange since we had no problems with data like histograms and datasets.

**Comment by tomkooij** [comment]
No only are pulsheights, mips, traces missing in the database (in all events I checked). There are almost no events and/or coinicidences created since Jan 1st, 2017. I requested a session from Oct 1st, 2017, and got only a single event, but it isn't even in the database. (Was it deleted?).

Can we purge the jsparc analysis session part of the postgress database and recreate it? (Yes, ofcourse we can, but is this a good idea? Will it even help at all?)

Am I correct that `Coincidences` and `Events` (django/postgress database, not ESD!) are created by requesting an analysis session and not by `/scripts/hisparc-update.py` ?

**Comment by 153957** [comment]
Correct, they are created by a cronjob:
https://github.com/HiSPARC/publicdb/blob/master/provisioning/publicdb.yml#L215
Which calls this endpoint:
https://github.com/HiSPARC/publicdb/blob/master/publicdb/analysissessions/urls.py#L12
Which calls this function:
https://github.com/HiSPARC/publicdb/blob/master/publicdb/analysissessions/views.py#L186

**Comment by tomkooij** [comment]
Are we logging the output of these jobs somewhere? `/var/log/cron` shows no errors, but there should be some output to `stdout`.

I just created another session and it is clearly wrong. I requested bunch of coincidences starting from Oct 1st and all I got was a single coincidence on Oct 12.

If I have some time tonight I will disable the cronjob and call the endpoint from a terminal to view the output.

So if cron is broken tomorrow, you know who to blame...

**Comment by tomkooij** [comment]
I checked the "raw" database: It has the base64 encoded zlib compressed pickles. They unpickle to sensible value.

The `to_python` function of `SerializedDataField` in `coincidences\models.py` is different from the  `SerializedDataField` in `histograms\models.py`. https://github.com/HiSPARC/publicdb/blob/master/publicdb/coincidences/models.py#L22

Why are those classes different? Why aren't we using a single definition of `SerializedDataField`?

I changed `coincidences/models.py` on my VM and it just works now. I'm changing `to_python` in `coincidences/models.py` on the server as well (as it only affect jSPARC that is already broken) and will create a PR for review.

**Comment by 153957** [comment]
Remember to commit/push your changes as well :P

**Comment by tomkooij** [comment]
It's just a hotfix. I'll prepare a real fix from my VM and setup a PR for review.

This hotfix will obviously not survive a `vagrant --provision` or `uppub` (as it does `git reset --hard origin/master`). So I'll try to find some time to push a real PR.
