### ISSUE TITLE
Database restore does not work in VM.

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#194]
I cannot successfully restore a postgresql database dump in my VM. I recall this happing months ago, but I attributed it to an old/stale install of my VM.

Today I destroyed my VM. `git reset --hard` to the current `origin/master`. Rebuild the VM and still the most recent database dump (Nov 1st) does not restore to a working server.

There always have been many (many!) warnings and errors, but now the station list is not restored, which means many of the other things also fail/are missing.

I use the command from README.md to restore (as user hisparc)

```
pg_restore --clean --if-exists --no-owner --no-acl --schema=public --dbname=publicdb /vagrant/publicdb_dump.sql
```
My copy of the database dump has the same MD5 hash as the dump on `trave`:
```
610e768a79ef7a926957f2de5e228223 *publicdb_dump.sql
```

This might be important: Will it work on `pique` if necessary?

**Comment by 153957** [comment]
See https://github.com/HiSPARC/publicdb/issues/189

**Comment by tomkooij** [comment]
I missed that one. I'm closing this one in favor of that other issue.
