### ISSUE TITLE
Allow provisioning of dev VMs without vault password

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#200]
(leftover from #190)

**Comment by tomkooij** [comment]
Now that I have the `ansible_local` provisioner running on Windows, this seems to be a non-issue.

**Comment by 153957** [comment]
Well

> 'Just removing the `vault_password_file=` in ansible.cfg'

is still an important step to get it to work.
Is is not also possible to create the file but leave it empty (or with a fake/wrong password)?

**Comment by tomkooij** [comment]
Well, we could create `./vault-password` in the publicdb mainfolder and **add it to gitignore**. 
With some contents like "Place vault password here".

**Comment by 153957** [comment]
Or maybe add the `vault_password_file` option to the ansible provisioner in the Vagrantfile, which points to some dummy file with a wrong/fake password. Which will then only be used for provisioning via vagrant.. That does mean that you should always provision dev machines via vagrant (unless you have a `~/.hisparc_vault`).

**Comment by tomkooij** [comment]
`vault_password_file` can be a script.

We can make it echo `~/.hisparc_vault` and add that to the repo. (It'll probably break on windows...)
