### ISSUE TITLE
uwsgi listen queue full

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#217]
In the last two weeks we have seen repeated "down-time" op `data.hisparc.nl`. When this occurs `pique` is not down, but `uwsgi` is not accepting requests. The log shows:

```
Sun Mar 18 10:09:36 2018 - *** uWSGI listen queue of socket "127.0.0.1:39579" (fd: 4) full !!! (101/100) ***
```

`collectreload` solves this.

Any thoughs on how to fix this? (Deploy nginx?)

**Comment by davidfokkema** [comment]
Ah, yes, I was going to mention that today as I was having trouble again this weekend. Without having investigated, I have no clue. When did this start happening?

**Comment by tomkooij** [comment]
From the logs it started as early as `Feb 27`. Perhaps earlier but no logs available.

**Comment by tomkooij** [comment]
Today it happend again.

The server load was very high (loadavgs >8). Memory full, swap almost full. Swapping 45% of the time. 

`collectreload` didn't work because the first part (./manage.py collectstatic) just wasn't running due to the high load.

A manual `sudo killall uwsgi && touch /tmp/uwsgi_reload.me` gave the uwsgi emperor just enough time to actually kill it's workers and restart:

```
Wed Mar 21 08:05:01 2018 - *** uWSGI listen queue of socket "127.0.0.1:32995" (fd: 3) full !!! (101/100) ***
Wed Mar 21 08:05:02 2018 - *** uWSGI listen queue of socket "127.0.0.1:32995" (fd: 3) full !!! (101/100) ***
Wed Mar 21 08:05:03 2018 - *** uWSGI listen queue of socket "127.0.0.1:32995" (fd: 3) full !!! (101/100) ***
Wed Mar 21 08:05:03 2018 - worker 6 (pid: 27246) is taking too much time to die...NO MERCY !!!
Wed Mar 21 08:05:04 2018 - *** uWSGI listen queue of socket "127.0.0.1:32995" (fd: 3) full !!! (101/100) ***
worker 6 buried after 1 seconds
binary reloading uWSGI...
```

NO MERCY. LOL.

**Comment by tomkooij** [comment]
Closed due to inactivity.
