### ISSUE TITLE
Deprecated signature algorithm MD5 in x509 certs

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#219]
In our `openssl.conf` we use `digest=md5`.

All our certs. Including our most recent cert on tietar (`tatestupgrade`) us MD5:

```
   Signature Algorithm: md5WithRSAEncryption
        Issuer: C=NL, ST=NH, L=Amsterdam, O=HiSPARC, Nikhef, OU=HiSPARC, CN=tietar.nikhef.nl/emailAddress=hisparc@nikhef.nl
        Validity
            Not Before: Jan 31 13:39:17 2018 GMT
            Not After : Jan 29 13:39:17 2028 GMT
        Subject: C=NL, ST=NH, O=HiSPARC, Nikhef, OU=HiSPARC, CN=tatatestupgrade/emailAddress=hisparc@nikhef.nl
```

**MD5 will be removed from OpenVPN in may 2018**

(The recently distrubuted `ca.crt` uses SHA1 -the current default CA signature algorithm)

**Comment by 153957** [comment]
So all certs with md5 will stop working then (if we upgrade OpenVPN)?

**Comment by tomkooij** [comment]
Yes, either OpenVPN op OpenSSL. OpenVPN is supposedly dropping MD5 after May 2018.

The OpenSSL in CentOS6 is 1.0.1 from Feb 2013. That still has MD5. But the OpenSSL in CentOS 7 does not have MD5 by default.

We will get bitten by this sooner or later.

So we need te renew all client certificates, not just the ones that are about to expire... :(

**Comment by davidfokkema** [comment]
This really is a pain. So we can't upgrade our certificates without upgrading to CentOS 7, and we can't upgrade to CentOS 7 before we upgrade our certificates? Paracetamol, anyone?

Seriously, though. Can we upgrade to CentOS 7 and (temporarily) enable MD5?

**Comment by tomkooij** [comment]
For OpenVPN we can keep using CentOS 6. We can easily issue new certificates using the current OpenSSL on CentOS 6. (But we need to force SHA2 as the current -old- OpenSSL uses the somewhat insecure SHA1, which will probably be dropped in a few years as well).

From browsing StackOverflow it seems possible to enable MD5 on CentOS 7. CentOS 7 would indeed solve #159.

But for now, I'll try to fix this using CentOS 6.

**Comment by tomkooij** [comment]
OpenSSL is current CentOS7 has OpenSSL 1.0.x (with MD5).
We have migrated all our certificates to SHA256 (but many MD5 certificates in use on clients). 

When we distribute new versions of the DAQ / installer we will distribute new certificates as well (and we can just mail them, since they are not secret). 

Closing.

**Comment by davidfokkema** [comment]
What about station certificates? They contain a private part which can’t be distributed by mail, right? I might be confusing a few things here.

**Comment by davidfokkema** [comment]
Ah, right.

**Comment by tomkooij** [comment]
Mmmmh.

It turns out that CentOS7 does have an OpenSSL that does not have MD5 enabled by default. It can be enabled. (tested in VM).

https://gist.github.com/rk295/25176f150c24f95df73e
