### ISSUE TITLE
Port to CentOS7

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#229]
Soon we will need to transfer `frome`, `pique` and `tietar` to a shiny new server that will provide "clean" CentOS7 VMs for each server.

I'm not sure we if we need to upgrade to CentOS7, but at this moment it seems necessary.

We will need to fix the provisioning scripts (and hopefully not much else) to run on CentOS7.

**Comment by 153957** [comment]
Start with changing the packer template to use a CentOS 7 box, use it for the local VMs (edit the Vagrantfile), then try to provision that and see what breaks.

**Comment by tomkooij** [comment]
Yep, my plan exactly. I'll have a go...

**Comment by 153957** [comment]
Implementation in #230
