### ISSUE TITLE
Switch to new machines

### ISSUE THREAD

**Issue by kaspervd** [HiSPARC/publicdb#238]
The new CentOS 7 (virtual) machines are ready. @davidfokkema @153957 @tomkooij and myself are able to login using their SSH keys. The machines have the following names and addresses:

| Hostname | IPv4 | IPv6 |
|---|----|-----|
| tietar-tmp.nikhef.nl | 192.16.186.201 | 2001:610:120:3003::186:201 |
| pique-tmp.nikhef.nl | 192.16.186.202 | 2001:610:120:3003::186:202 |
| frome-tmp.nikhef.nl | 192.16.186.203 | 2001:610:120:3003::186:203 |
| neckar-tmp.nikhef.nl | 192.16.186.205 | 2001:610:120:3003::186:205 |

The machines frome-tmp, tietar-tmp and pique-tmp all have a locked root and hisparc user, so it is only possible to login using your SSH-key. Neckar-tmp only has a non-locked root user and is of later concern. In time the names will be changed to $HOST instead of $HOST-tmp.

I propose the following approach to provision the new machines (starting with pique):

- [x] Find out all references to the old IP addresses or machine name.
    - Host names in ssh tunnel script
    - Host names in Ansible inventory files
    - IP address of pique in shorewall installation on tietar
    - IP address of tietar in provisioning/roles/network-tietar/tasks/main.yml
    - provisioning/host_vars/pique.nikhef.nl/main.yml **(don't change)**
    - provisioning/roles/openvpn/files/openvpn/client/server.crt **(don't change)**
- [x] Change all old IP addresses to new ones, change $HOST to $HOST-tmp in the [Migrate to CentOS 7](https://github.com/HiSPARC/publicdb/pull/230) pull request.
    - [ ] Does GATEWAY=192.16.192.80 still hold in provisioning/roles/network-tietar/tasks/main.yml?
- [x] Merge the [the pull request](https://github.com/HiSPARC/publicdb/pull/230). Testing / debugging nagios can be done on the new machine.
- [x] Provision pique-tmp.
- [x] Check if everything works correctly.
- [x] Provision other machines.
- [x] Change host names to $HOST, in code and the actual machine names
- [x] Update DNS
- [x] Deactivate old pique
- [x] Copy up to date database to new server
- [x] Copy up to date ESD to new server
- [x] Deactivate old frome
- [ ] Deactivate old tietar
- [x] merge the (extra) changes to `settings.py` on pique into this repo. 
- [ ] set userid and groupid of hisparc in playbook
- [x] add tivoli tsm client to the new frome #239
- [x] commit 'w' to 'wb' change in xml-rpc server
- [x] commit hisparcvpnd changes
- [ ] fix huge nagios logs in /var/log/nagios/archive/

What do you @davidfokkema, @153957, @tomkooij think of this approach? How do I make sure pique-tmp and pique don't open the same raw data HDF5 file? Are there other problems I overlook?

**Comment by 153957** [comment]
> How do I make sure pique-tmp and pique don't open the same raw data HDF5 file?

By not (yet) mounting the `/databases` mount (i.e. `trave:/export/hisparc/databases`) on the new machine. and simply changing the DATASTORE_PATH in the settings to some other location.

**Comment by kaspervd** [comment]
The latest version seems to work fine. Thanks for the clarification.

**Comment by 153957** [comment]
The latest version (master) is not yet deployed on the current pique.

**Comment by kaspervd** [comment]
Update since 7/9/2018 when @153957 and @davidfokkema were at Nikhef:
- We ran into connectivity problems which are now resolved.
- During provisioning of PIQUE-TMP on 10/9/2018 the machine crashed. This had to do with the CentOS 7 kernel that was used:  kernel-3.10.0-862 = unsafe, kernel-3.10.0-514 = safe.
- The PostgreSQL RPM was for RHEL 6, the machine crashed when trying to install the PostgreSQL server. I manually removed both the installed server and the RPM and switched to RHEL 7. This seems to work.
- Now, during provisioning the SSH connection randomly drops. Very similar to [this issue](https://github.com/ansible/ansible/issues/17935) but the proposed solution does not work. I use ansible-playbook 2.6.4 in combination with python 2.7.15. Unfortunately this issue is still open. I often get to TASK [publicdb : checkout jsparc in /srv/publicdb/jsparc] but not always.

**Comment by kaspervd** [comment]
Not too well indeed, but I think it has to do with Ansible and not our playbooks.. When trying to install the postgreSQL-server the machine kicked me out and I was unable to SSH back in again. After several minutes or so I could get back in. Note that this problem was reproducible (again waiting several minutes before everything was fine). The current problem is completely random unfortunately.. (the installation of PostgreSQL was one of the early steps, the random connection drop occurs a bit later)

**Comment by davidfokkema** [comment]
How does passing ``-k`` work? The account password is disabled, right?

**Comment by kaspervd** [comment]
Correct, but now it asks for my SSH-key passphrase. Without -k it gets the passphrase from ssh-agent but apparently that's not very stable?

**Comment by kaspervd** [comment]
Some updates:
- Again http and https ports were closed (for PIQUE-TMP although we were very explicit).
- The problem with kernel-3.10.0-862 (i.e. yum updates everything including a new but non-working kernel) was solved by removing the 862 boot option in /boot/grub2/grub.cfg -> I've applied to same solution to FROME-TMP and TIETAR-TMP.
- PIQUE-TMP and FROME-TMP have been provisioned successfully
- TIETAR-TMP already has static networking, so I've changed /etc/sysconfig/network-scripts/ifcfg-em1 to /etc/sysconfig/network-scripts/ifcfg-eth0 in the ansible script.
- I've encountered a new ansible bug in which the role handler 'reboot' is not found. Again, many other users experience the same problem. Haven't fixed it yet.

Most importantly:
- CT wants our access to TRAVE: "De toegang tot frome is beperkt omdat deze binnen
de core servers van Nikhef valt. Hier zullen waarschijnlijk data vanaf
gehaald moeten worden. Kan je aangeven welke dat zijn? Hopelijk kunnen Daniel
(en ik) deze dan tijdelijk via een andere weg beschikbaar maken. Dit zal
mogelijk niet via NFS gaan maar daar kijken we nog naar."

**Comment by 153957** [comment]
- What did the "862 boot option" do? Is it safe to remove it?
- Which version of Ansible are you using?

**Comment by kaspervd** [comment]
The new 862 kernel fails to boot on the hypervisor. I use ansible-playbook 2.6.4 in combination with python 2.7.15.

**Comment by 153957** [comment]
What is the current status? Have you gotten further with provisioning the new machines?

**Comment by kaspervd** [comment]
Pique has been provisioned and renamed, so data.hisparc.nl now points to the new machine. Unfortunately I'm still experiencing some problems with the daily update.

Frome has been provisioned and after I fixed the problems with pique I can start migrating.

Tietar is giving several problems when trying to provision. I'll try to fix that when pique and frome are working properly.

**Comment by kaspervd** [comment]
I had to change the userid and groupid of "hisparc" in order to get access to the LDAP domain nikhef.nl:

usermod -u 7712 hisparc
groupmod -g 7100 hisparc

find / -group 1000 -exec chgrp -h hisparc {} \;
find / -user 1000 -exec chown -h hisparc {} \;

This also needs to be changed in our playbooks.

**Comment by davidfokkema** [comment]
What happens to files which were created with the old uid/gid?

**Comment by kaspervd** [comment]
Those files were found and changed:

find / -group 1000 -exec chgrp -h hisparc {} ;
find / -user 1000 -exec chown -h hisparc {} ;

The -exec command executes chgrp or chmod command on each file. The -h option passed to the chgrp/chmod command affect each symbolic link instead of any referenced file.

**Comment by 153957** [comment]
Instead of `find` you can just use `chown` directly, for both owner and group:

```
chown --recursive --no-dereference --from=1000 hisparc /
chown --recursive --no-dereference --from=:1000 :hisparc /
```

**Comment by davidfokkema** [comment]
I have never, ever, heard of the ``--from`` option before. 🤯

**Comment by kaspervd** [comment]
Haha, I've also had that feeling a couple of times over the last several weeks..

**Comment by kaspervd** [comment]
The machine already has an IPv4 address and outside the Nikhef network the DNS points to this IPv4 address. So no problems there. However, inside Nikhef it points to an IPv6 address.. I contacted Jan Just from CT and he saw no reason to configure for IPv6 so I guess I need to make sure that the local Nikhef DNS also uses the IPv4 address..

**Comment by kaspervd** [comment]
After a long and tedious period of learning how to work with numerous software packages and a lot of debugging the migration has finally been completed :) Several problems persist but I will open separate issues for them.

**Comment by 153957** [comment]
@kaspervd Remember to ask for help/guidance if you get really stuck 😉
