### ISSUE TITLE
Include tivoli tsm backup client in datastore/frome

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#239]
The good old frome runs `tivoli tsm` to backup the raw datastore to Vancis. This was (is) installed and managed by CT.

We should install and manage this ourselves on the new frome. It should be included in the provisioning of datastore (frome).

**Comment by kaspervd** [comment]
It is installed on the new Frome now but is not yet part of our provisioning playbooks

**Comment by tomkooij** [comment]
Backups are handled by CT so not relevant anymore.
