### ISSUE TITLE
Correct userid and groupid in playbooks

### ISSUE THREAD

**Issue by kaspervd** [HiSPARC/publicdb#240]
It would be nice if our provisioning automatically creates the hisparc user with the right userid and groupid. These ids are needed to access trave.nikhef.nl via NFS.

They are:
uid=7712(hisparc)
gid=7100(hisparc)

**Comment by tomkooij** [comment]
This is not an ansible issue. We provision server with the user `hisparc` already created. We could change it in our dev VMs. But we (sadly) do not use our dev images on our live machines.

**Comment by tomkooij** [comment]
The common playbook now checks if hisparc uid:gid is correct before starting provisioning. Hopefully this will save us next time. Fixed in 2e39a57
