### ISSUE TITLE
Unable to send mails from servers

### ISSUE THREAD

**Issue by kaspervd** [HiSPARC/publicdb#241]
Our new servers are now within a subnet and we're not allowed to access the Nikhef mail server anymore (smtp.nikhef.nl). This means that we're not able to:
- send emails to jsparc users
- send nagios mails
- send mails to the publicdb admins of something goes wrong
- send mails to beheer@hisparc.nl if a station-layout needs to be accepted

CT has now allowed us to mail to all @nikhef.nl addresses. This solves the admin mail problem, the other issues are still open..

**Comment by 153957** [comment]
We should be able to configure Django to send emails using a Nikhef account (maybe using the Beheer account?)

https://docs.djangoproject.com/en/2.1/topics/email/#smtp-backend
https://wiki.nikhef.nl/ct/Mail_client_settings

**Comment by tomkooij** [comment]
As of April 13th 2019, `smtp.nikhef.nl` has whitelisted mail relaying from `bhrhispa@nikhef.nl` (without authentication)
