### ISSUE TITLE
Very slow API

### ISSUE THREAD

**Issue by kaspervd** [HiSPARC/publicdb#243]
Somehow, since the server migration the publicdb API is very slow. Very simple requests take minutes. The upside, it does work if you wait long enough :')

**Comment by 153957** [comment]
Which parts are very slow? I just manually tried some endpoints without issues.

Perhaps it becomes slow under heavy load?

**Comment by kaspervd** [comment]
Oh wow, hm that's interesting. An example which takes over a minut:

`from sapphire import Network`
`print(Network().station_numbers())`

**Comment by 153957** [comment]
Strange, that should simply call this endpoint and extract the numbers from that JSON: http://data.hisparc.nl/api/stations/
This loads quickly without any significant delay for me.

**Comment by kaspervd** [comment]
Ok, that's very good to hear! I'll try to investigate why it only happens here (Niek also suffers from this)

**Comment by 153957** [comment]
Directly opening that url in a browser is also slow for you? (I did not check yet by using sapphire)

**Comment by kaspervd** [comment]
No, that's really fast. Weird..

**Comment by 153957** [comment]
Via sapphire is also super fast here, no issues.

**Comment by kaspervd** [comment]
Ok, thnx. I'll close this issue then and try to figure out what's wrong over here

**Comment by kaspervd** [comment]
It only happens when I'm on the Nikhef network so it's definitely a local problem

**Comment by kaspervd** [comment]
Probably due to IPv6, @153957 is it possible to refuse IPv6 in Django?

**Comment by 153957** [comment]
That should be handled at a different level, nginx or DNS. But that does not seem like the best fix..

**Comment by 153957** [comment]
Could you try running this (in a Terminal) while on the Nikhef network and while not on it:
`dig data.hisparc.nl aaaa`,
and post the results here (I'm mostly interested in the 'Query time' part of the result).

**Comment by kaspervd** [comment]
;; Query time: 4 msec
;; SERVER: 192.16.199.17#53(192.16.199.17)
;; WHEN: Tue Jan 15 10:03:04 CET 2019
;; MSG SIZE  rcvd: 373

**Comment by 153957** [comment]
That seems fast enough, so not likely a DNS issue.

**Comment by tomkooij** [comment]
We now handle IPv6 using nginx, so I'm pretty sure this is fixed. Closing until further notice.
