### ISSUE TITLE
Configuration of Nagios fails

### ISSUE THREAD

**Issue by kaspervd** [HiSPARC/publicdb#244]
After a successful installation of nagios on tietar.nikhef.nl I'm not able to correctly configure everything. This is probably due to a lack of understanding of nagios.

However, if nagios / nsca is running on the server, several 1000s of send_nsca processes are started on the station pc's eventually leading to a crash of the station pc. This makes that nagios / nsca should only be started if we're really certain it will work.

**Comment by 153957** [comment]
Related discussions:
- https://github.com/HiSPARC/publicdb/pull/230#pullrequestreview-132956958
- https://github.com/HiSPARC/publicdb/commit/5229a471fc550eb3b76ae5baee36622c08809442

**Comment by kaspervd** [comment]
Essentially the same problem but the solution in https://github.com/HiSPARC/publicdb/pull/119 cannot be used since nsca version 2.6.2 is not available for CentOS7

**Comment by tomkooij** [comment]
NSCA fixed in #248

TODO: Make sure `hisparcvpnd` is able to modify the nagios config within SELinux policies.

**Comment by tomkooij** [comment]
Seems fine.
