### ISSUE TITLE
Remove Nagios log files

### ISSUE THREAD

**Issue by kaspervd** [HiSPARC/publicdb#245]
Nagios has been running (incorrectly configured) for some time on the new machines. Per day there was a ~100 MB log file created. After Nagios is configured correctly (see https://github.com/HiSPARC/publicdb/issues/244), it would also be nice if these log files are deleted after some time.

**Comment by tomkooij** [comment]
There has been a cron job doing this for years: e59ce4015ff1a889d425b79a14f6d2cefd01456b
