### ISSUE TITLE
data.hisparc.nl image download broken in Chrome

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#262]
Chrome has appearantly dropped support for "top frame navigation" which means that (using Chrome) hisogram images can no longer be downloaded.

This affects the javascript function `downloadGraph` that we use on several pages: [example](https://github.com/HiSPARC/publicdb/blob/cd33a6a1ac617a3ac60e3c41c657989e7ec778f5/publicdb/status_display/templates/status_display/station_data.html#L27)

Fix:
https://stackoverflow.com/questions/45493234/jspdf-not-allowed-to-navigate-top-frame-to-data-url

**Comment by 153957** [comment]
Just instruct users to take a screenshot 😄

**Comment by tomkooij** [comment]
won't fix
