### ISSUE TITLE
Use a less restrictive data license

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#275]
Why was the license for data usage changed to a more restrictive one in f68b97c34043786bbf196f0bccf179512712e484 and 094fc492bc794545add39a49430ecc8ae11edfd5 ? Can you give examples of cases where the old license was a problem? Does this have to do with funding for the project, or is it based on general institute/university rules?

*edit: referenced an additional commit*

**Comment by 153957** [comment]
I am aware of this paper: https://arxiv.org/abs/1808.10645 which had the following comment:
> Comments: The paper lacks permission from the HiSPARC organization for the data

Is that what triggered this change?

**Comment by tomkooij** [comment]
That was the main incident that triggered the change, but we've had people downloading the entire ESD before.

**Comment by 153957** [comment]
The downloading is not prevented by this license change.. there is no fair use policy, or rate limiting..

Do you have any idea who those people were, and what their goals/use of the data was?
Were the attribution and share alike clauses not good enough?

What is the current license when used within the collaboration or for education? The text "is licensed for use within" does not clarify what the rights and restrictions are when using the data.

Was any data misrepresented in that paper? And that paper does seem to have had input from people at the University of Bristol, who I believe are part of the HiSPARC collaboration, so what went wrong there?

**Comment by 153957** [comment]
@HiSPARC/coders

**Comment by 153957** [comment]
@vaneijk responded privately. Here is a small summary;

The take away from that was that he does not want others to use any data from the HiSPARC project, unless they also contribute something to the project, either taking responsibility over something, or providing support. And "HiSPARC is not a charity".

Additionally, he does not want there to be any publications using HiSPARC data containing errors due to not being properly informed, especially if those mention HiSPARC (or its collaborators).

**Comment by 153957** [comment]
Fixed in #278
