### ISSUE TITLE
Add PATH to crontab

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#277]
`/etc/cron.d/hisparc` is managed by ansible. 

However `certbot renew` fails because of an PATH issue.

Fix: add `PATH=/opt/miniconda/bin:/opt/miniconda/bin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin` to the top of the file.

This is now the case (and works) on both pique and tietar, but needs to be added to the provisioning.

**Comment by 153957** [comment]
`/opt/miniconda/bin` only once should be fine 😄
