### ISSUE TITLE
Pulseheight unit: millivolt vs ADC counts

### ISSUE THREAD

**Issue by cblam** [HiSPARC/publicdb#45]
The pulseheight histogram on the station overview page is currently shown as number-of-events vs pulseheight-in-millivolt.

If we check the pulseheight most-probable-value via the station status page (nagios), the MPV is stated in units of ADC counts (without mentioning the unit).

This discrepancy in usage of units is confusing, even if the units are stated. Converting between units is a menial task. Therefore it is suggested to use only one unit everywhere for the pulseheight.

**Comment by 153957** [comment]
Moreover; the [`histograms.esd.get_pulseheights`](https://github.com/HiSPARC/publicdb/blob/master/django_publicdb/histograms/esd.py#L336) function used to retrieve pulseheights uses the (relative) ADC to mV conversion based on HiSPARC II electronics, i.e. 0.57. So it is incorrect for most HiSPARC III stations..

**Comment by 153957** [comment]
@kaspervd @davidfokkema @tomkooij - What do you think about this?

**Comment by davidfokkema** [comment]
I say let's use ADC counts. Or maybe there is another, more correct, name for the value obtained from an ADC. I've seen 'channel'.

**Comment by tomkooij** [comment]
We measure ADC, so let's use ADC. Using mV seems to imply it's an actual potential difference but it isn't.
