### ISSUE TITLE
Update provisioning to create a production and a 'stage' server

### ISSUE THREAD

**Issue by jorianvo** [HiSPARC/publicdb#71]
The current problem is that the provisioning does a single `git checkout publicdb` on the master branch, therefore you have to switch to your testing branch after every `vagrant provision`. 
Symlinking `/vagrant` to `/srv/publicdb/www` works, but you still have to commit all your changes to your testing branch else the `checkout` will fail.

**Comment by 153957** [comment]
Kinda fixed by #95
